version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: brief_11
      DB_USERNAME: dev
      DB_PASSWORD: 1234
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: brief_11
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
