spring:
    profiles:
        active: prod  # Change to 'prod' for production environment
    main:
        allow-bean-definition-overriding: true
    datasource:
        url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:brief_11}
        username: ${DB_USERNAME:dev}
        password: ${DB_PASSWORD:1234}
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
    session:
        store-type: jdbc
        jdbc:
            initialize-schema: always
            table-name: SPRING_SESSION

server:
    port: ${SERVER_PORT:8081}
    servlet:
        session:
            timeout: 30m

---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:brief_11}
    jpa:
        show-sql: true

logging:
    level:
        org.springframework.security: DEBUG

---
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:brief_11}
        username: ${DB_USERNAME:dev}
        password: ${DB_PASSWORD:1234}
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false

logging:
    level:
        org.springframework.security: INFO

